### PR TITLE
initial entity model for oauth user

### PR DESCRIPTION
**Pull request by kilyinov**
Hi guys - i'm experimenting with wiring in oauth authentication, this is a first step in allowing user object of oauth kind to be persisted

### CODE REVIEW

**Comment by seanelias** [comment]
@kamsonline you have some conflicts with master on this branch.

**Comment by afcastano** [comment]
Is this still valid? It has one commit by Kosta a few months ago....

@seanelias @kamsonline

**Comment by kilyinov** [comment]
May not be valid anymore

**Comment by mbyrne00** [comment]
No longer relevant ... closing

**Pull request closed without merging**
